/* 由 tools/sync_album_catalog.mjs 从照片台账生成，请勿手改。 */
export const ALBUM_PHOTOS = {
  "duck": {
    "file": "assets/album/duck.jpg",
    "kind": "actual",
    "title": "File:Nanjing Salted Duck.jpg",
    "caption": "南京盐水鸭实拍",
    "author": "AddisWang",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nanjing_Salted_Duck.jpg",
    "width": 1200,
    "height": 795,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "fans": {
    "file": "assets/album/fans.jpg",
    "kind": "actual",
    "title": "File:Duck blood and vermicelli soup (20150819124849).JPG",
    "caption": "南京鸭血粉丝汤实拍",
    "author": "N509FZ",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Duck_blood_and_vermicelli_soup_(20150819124849).JPG",
    "width": 1200,
    "height": 900,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "tea": {
    "file": null,
    "kind": "missing"
  },
  "taro": {
    "file": "assets/album/taro.jpg",
    "kind": "actual",
    "title": "File:Tangyumiao.JPG",
    "caption": "南京糖芋苗实拍",
    "author": "AddisWang",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tangyumiao.JPG",
    "width": 1200,
    "height": 900,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "pot": {
    "file": "assets/album/pot.jpg",
    "kind": "actual",
    "title": "File:Beef potstickers.jpg",
    "caption": "牛肉锅贴实拍；原图拍摄于常州，不代表南京或图鉴所列店铺",
    "author": "Fumikas Sagisavas",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Beef_potstickers.jpg",
    "width": 960,
    "height": 960,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "bean": {
    "file": "assets/album/bean.jpg",
    "kind": "actual",
    "title": "File:赤豆酒酿元宵.jpg",
    "caption": "南京赤豆酒酿元宵实拍",
    "author": "三猎",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E8%B5%A4%E8%B1%86%E9%85%92%E9%85%BF%E5%85%83%E5%AE%B5.jpg",
    "width": 1200,
    "height": 799,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "cake": {
    "file": null,
    "kind": "missing"
  },
  "root": {
    "file": "assets/album/root.jpg",
    "kind": "related",
    "title": "File:糖藕.jpg",
    "caption": "糯米糖藕实拍，用于认识藕中灌米的做法；不是完整的南京糖粥藕",
    "author": "三猎",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E7%B3%96%E8%97%95.jpg",
    "width": 972,
    "height": 1200,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "egg": {
    "file": "assets/album/egg.jpg",
    "kind": "documentary",
    "title": "File:Wàng jīdàn.jpg",
    "caption": "南京旺鸡蛋摊位纪实（2010）；照片不能确认胚龄，不作十二日活珠子实物认定",
    "author": "Berthe",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:W%C3%A0ng_j%C4%ABd%C3%A0n.jpg",
    "width": 1000,
    "height": 750,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "bao": {
    "file": "assets/album/bao.jpg",
    "kind": "actual",
    "title": "File:Xiaolongbaozi (Nanjing).jpg",
    "caption": "南京小笼包实拍；不代表图鉴所列店铺",
    "author": "Leiem",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Xiaolongbaozi_(Nanjing).jpg",
    "width": 1200,
    "height": 900,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "xiangdu": {
    "file": null,
    "kind": "missing"
  },
  "luhao": {
    "file": "assets/album/luhao.jpg",
    "kind": "actual",
    "title": "File:Artemisia selengensis bundles.jpg",
    "caption": "芦蒿菜蔬实拍（Artemisia selengensis）；不作南京拍摄地点认定",
    "author": "Fumikas Sagisavas",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Artemisia_selengensis_bundles.jpg",
    "width": 900,
    "height": 1200,
    "changes": "按 EXIF 方向旋转，等比缩至最长边 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "wufan": {
    "file": "assets/album/wufan.jpg",
    "kind": "actual",
    "title": "File:乌米饭 20240505.jpg",
    "caption": "乌米饭实拍；不作南京拍摄地点认定",
    "author": "Uuongkinghe",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E4%B9%8C%E7%B1%B3%E9%A5%AD_20240505.jpg",
    "width": 1200,
    "height": 900,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "zhuangyuan": {
    "file": null,
    "kind": "missing"
  },
  "cloud": {
    "file": "assets/album/cloud.jpg",
    "kind": "actual",
    "title": "File:Drachenrobe-Qianlong.JPG",
    "caption": "云锦实物：德国莱比锡格拉西博物馆藏乾隆时期龙袍；不是南京现场摄影",
    "author": "Dr. Meierhofer",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Drachenrobe-Qianlong.JPG",
    "width": 960,
    "height": 1140,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "gold": {
    "file": null,
    "kind": "missing"
  },
  "lamp": {
    "file": "assets/album/lamp.jpg",
    "kind": "actual",
    "title": "File:Night of Qinhuai lantern fair 2019 - decorations.jpg",
    "caption": "2019 年秦淮灯会花灯实景",
    "author": "Leiem",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Night_of_Qinhuai_lantern_fair_2019_-_decorations.jpg",
    "width": 960,
    "height": 720,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "ronghua": {
    "file": null,
    "kind": "missing"
  },
  "zheshan": {
    "file": null,
    "kind": "missing"
  },
  "jianzhi": {
    "file": null,
    "kind": "missing"
  },
  "kejing": {
    "file": "assets/album/kejing.jpg",
    "kind": "related",
    "title": "File:Kejingchu in Nanjing 2012-02.JPG",
    "caption": "金陵刻经处大门实景；用于认识传承地点，不是雕版实物",
    "author": "猫猫的日记本",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kejingchu_in_Nanjing_2012-02.JPG",
    "width": 960,
    "height": 720,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "baiju": {
    "file": null,
    "kind": "missing"
  },
  "elephant": {
    "file": "assets/album/elephant.jpg",
    "kind": "actual",
    "title": "File:Stone Elephant Road (Ming Xiaoling) 1.jpg",
    "caption": "南京明孝陵石象路实景",
    "author": "钉钉",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stone_Elephant_Road_(Ming_Xiaoling)_1.jpg",
    "width": 960,
    "height": 720,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "book": {
    "file": "assets/album/book.jpg",
    "kind": "actual",
    "title": "File:Facade of Libraire Avant-Garde(Wutai Mountain branch).jpg",
    "caption": "先锋书店五台山店外观；仅作地点介绍，不代表合作或推荐",
    "author": "JosephLai",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Facade_of_Libraire_Avant-Garde(Wutai_Mountain_branch).jpg",
    "width": 1200,
    "height": 1200,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "pibie": {
    "file": "assets/album/pibie.jpg",
    "kind": "actual",
    "title": "File:Tomb of Xiao Jing - Bixie.JPG",
    "caption": "南京萧景墓前南朝石辟邪实拍",
    "author": "Shallowell",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tomb_of_Xiao_Jing_-_Bixie.JPG",
    "width": 900,
    "height": 1200,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "wadang": {
    "file": null,
    "kind": "missing"
  },
  "chengzhuan": {
    "file": "assets/album/chengzhuan.jpg",
    "kind": "actual",
    "title": "File:Nanjing City Wall Brick with Maker's Mark (10150966183).jpg",
    "caption": "南京明城墙带制作者铭文的城砖实拍",
    "author": "Gary Todd from Xinzheng, China",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nanjing_City_Wall_Brick_with_Maker%27s_Mark_(10150966183).jpg",
    "width": 960,
    "height": 640,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "nanyanjing": {
    "file": "assets/album/nanyanjing.jpg",
    "kind": "actual",
    "title": "File:Full view of Nanjing Eye Pedestrian Bridge.jpg",
    "caption": "南京眼步行桥实景",
    "author": "Uyiliu2",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Full_view_of_Nanjing_Eye_Pedestrian_Bridge.jpg",
    "width": 500,
    "height": 376,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "baoenta": {
    "file": "assets/album/baoenta.jpg",
    "kind": "actual",
    "title": "File:2024Apr - Glass Pagoda of Nanjing - img 01.jpg",
    "caption": "大报恩寺遗址公园现建塔实景（2024）；不是明代原塔",
    "author": "Chainwit.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2024Apr_-_Glass_Pagoda_of_Nanjing_-_img_01.jpg",
    "width": 960,
    "height": 720,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "zifeng": {
    "file": "assets/album/zifeng.jpg",
    "kind": "actual",
    "title": "File:Zifeng Tower in 2017.jpg",
    "caption": "南京紫峰大厦实景",
    "author": "Haha169",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zifeng_Tower_in_2017.jpg",
    "width": 675,
    "height": 1200,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "baochuan": {
    "file": "assets/album/baochuan.jpg",
    "kind": "reconstruction",
    "title": "File:Nanjing Treasure Boat - P1070978.JPG",
    "caption": "南京宝船厂遗址的宝船复原展示；不是明代原船",
    "author": "User:Vmenkov",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nanjing_Treasure_Boat_-_P1070978.JPG",
    "width": 960,
    "height": 720,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "plum": {
    "file": "assets/album/plum.jpg",
    "kind": "actual",
    "title": "File:2019南京梅花山梅花02.jpg",
    "caption": "南京梅花山梅花实拍（2019）",
    "author": "西安兵马俑",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2019%E5%8D%97%E4%BA%AC%E6%A2%85%E8%8A%B1%E5%B1%B1%E6%A2%85%E8%8A%B102.jpg",
    "width": 960,
    "height": 719,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "sakura": {
    "file": "assets/album/sakura.jpg",
    "kind": "actual",
    "title": "File:南京玄武区鸡鸣寺路樱花 - panoramio.jpg",
    "caption": "南京鸡鸣寺路樱花实景",
    "author": "helkonig",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E5%8D%97%E4%BA%AC%E7%8E%84%E6%AD%A6%E5%8C%BA%E9%B8%A1%E9%B8%A3%E5%AF%BA%E8%B7%AF%E6%A8%B1%E8%8A%B1_-_panoramio.jpg",
    "width": 900,
    "height": 1200,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "leaf": {
    "file": "assets/album/leaf.jpg",
    "kind": "actual",
    "title": "File:Foglia di platanus x acerifolia.jpg",
    "caption": "二球悬铃木叶片实拍，俗称法国梧桐；不是南京现场摄影",
    "author": "Arlas!",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Foglia_di_platanus_x_acerifolia.jpg",
    "width": 250,
    "height": 211,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "stone": {
    "file": "assets/album/stone.jpg",
    "kind": "documentary",
    "title": "File:南京雨花台雨花石.jpg",
    "caption": "南京雨花台雨花石陈列实景（打磨后的观赏石）",
    "author": "董辰兴",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E5%8D%97%E4%BA%AC%E9%9B%A8%E8%8A%B1%E5%8F%B0%E9%9B%A8%E8%8A%B1%E7%9F%B3.jpg",
    "width": 960,
    "height": 640,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "guihua": {
    "file": "assets/album/guihua.jpg",
    "kind": "actual",
    "title": "File:Osmanthus fragrans flowers.jpg",
    "caption": "桂花（Osmanthus fragrans）花朵实拍；不作南京拍摄地点认定",
    "author": "Achillu",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Osmanthus_fragrans_flowers.jpg",
    "width": 900,
    "height": 1200,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "baige": {
    "file": "assets/album/baige.jpg",
    "kind": "documentary",
    "title": "File:Music Stage of Sun Yat-sen Mauloleum.jpg",
    "caption": "南京中山陵音乐台白鸽与场地实景",
    "author": "Jay Hsu",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Music_Stage_of_Sun_Yat-sen_Mauloleum.jpg",
    "width": 960,
    "height": 646,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "yinghuo": {
    "file": "assets/album/yinghuo.jpg",
    "kind": "related",
    "title": "File:반딧불이.jpg",
    "caption": "萤科昆虫（Pyrocoelia rufa）实拍，仅作形态对照；不是南京灵谷寺现场或当地物种认定",
    "author": "메이",
    "license": "CC BY-SA 1.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/1.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%EB%B0%98%EB%94%A7%EB%B6%88%EC%9D%B4.jpg",
    "width": 250,
    "height": 187,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "hufengdie": {
    "file": "assets/album/hufengdie.jpg",
    "kind": "actual",
    "title": "File:Leuhd204.jpg",
    "caption": "中华虎凤蝶（Luehdorfia chinensis）标本实拍；不是南京野外摄影",
    "author": "Notafly",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leuhd204.jpg",
    "width": 960,
    "height": 720,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  },
  "jiangtun": {
    "file": "assets/album/jiangtun.jpg",
    "kind": "actual",
    "title": "File:Yangtze finless porpoise, 12 February 2008a.jpg",
    "caption": "长江江豚实拍，摄于中国科学院水生生物研究所（2008）；不是南京江段野外摄影",
    "author": "Huangdan2060",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yangtze_finless_porpoise,_12_February_2008a.jpg",
    "width": 960,
    "height": 864,
    "changes": "采用 Commons 提供的缩略图；按 EXIF 方向旋转，等比缩至最长边不超过 1200px，JPEG 85 重编码并移除嵌入元数据；未裁剪、未改色。"
  }
};
